import express from "express";
import cors from "cors";
import { tenantGuard } from "./middlewares/tenantGuard";
import { adminGuard } from "./middlewares/adminGuard";
import {
  createTenantItem,
  getTenantItems,
  triggerItemTransition,
} from "./controllers/itemController";
import { SlaDaemon } from "./services/slaDaemon";
import { createTenantDelegation, getPendingUserApprovals, processApprovalAction } from "./controllers/approvalController";
import { getItemAuditTimeline } from "./controllers/auditController";
import { createNewTenantWorkflow, getActiveTenantWorkflows } from "./controllers/adminWorkflowController";
import { validateBody, createWorkflowSchema, transitionItemSchema, resolveApprovalSchema } from './middlewares/validate';

const app = express();
const PORT = process.env.PORT || 8000;

const allowedOriginsSetting = process.env.ALLOWED_ORIGINS 
  ? process.env.ALLOWED_ORIGINS.split(',') 
  : ['http://localhost:5173'];

app.use(cors({
  origin: function (origin, callback) {
    // Allow standard local machine test environments or tool clients (Postman)
    if (!origin) return callback(null, true);
    
    // Allow any custom production domains you inject via Render configuration panels
    if (allowedOriginsSetting.indexOf(origin) !== -1) {
      return callback(null, true);
    }
    
    // Dynamic Safeguard: Match any deployment subdomains generated by Vercel automatically
    if (origin.endsWith('.vercel.app')) {
      return callback(null, true);
    }
    
    // Reject unauthorized or suspicious third-party endpoint domains
    return callback(new Error('Security Block: This origin sits outside company access groups.'), false);
  },
  credentials: true,
  methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
}));

app.use(express.json());

// Base Server Health Check Endpoint
app.get("/api/health", (req, res) => {
  res.json({ status: "online", engine: "Emaar Enterprise Integration Hub" });
});

app.get("/api/items", tenantGuard, getTenantItems);
app.post('/api/items/transition', tenantGuard, validateBody(transitionItemSchema), triggerItemTransition);
app.post('/api/approvals/resolve', tenantGuard, validateBody(resolveApprovalSchema), processApprovalAction);
app.post('/api/workflows/configure', tenantGuard, adminGuard, validateBody(createWorkflowSchema), createNewTenantWorkflow);
app.get('/api/approvals/pending', tenantGuard, getPendingUserApprovals);
app.post('/api/items', tenantGuard, createTenantItem);
app.post('/api/approvals/delegate', tenantGuard, createTenantDelegation);
app.get('/api/audit-logs/:itemId', tenantGuard, getItemAuditTimeline);
app.get('/api/workflows/active', tenantGuard, getActiveTenantWorkflows);


app.listen(PORT, () => {
  console.log(
    `Core Server running smoothly on network register: http://localhost:${PORT}`,
  );
  const slaEngine = new SlaDaemon();
  slaEngine.start(60000);
});
